---
name: Docker Build/Publish

on:
  push:
    tags:
    - 'v*'

jobs:   
  build:    
    runs-on: ubuntu-20.04    
    env:      
      DOCKER_REGISTRY: registry.hub.docker.com
      DOCKER_IMAGE: chhaley/omada_exporter     
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}                
    steps:    
    - name: Checkout the code       
      uses: actions/checkout@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login      
      if: success()      
      run: |        
        echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin   

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2.8.1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
